apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
    env: staging
  name: nginx-pod
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
     requests:
      cpu: 100m
      memory: 100Mi
    ports:
    - containerPort: 80
  restartPolicy: Never
